# .github/workflows/sql-workflow.yml
on:
 #workflow_dispatch:
 push:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Script
      run: ./ps/genSql.ps1
      shell: pwsh
